lista =[]
lista.append('L')
lista.append('I')
lista.append('F')
lista.append('E')
lista.append(' ')
lista.append('I')
lista.append('S')
lista.append(' ')
lista.append('N')
lista.append('O')
lista.append('T')
lista.append(' ')
lista.append('A')
lista.append(' ')
lista.append('P')
lista.append('R')
lista.append('O')
lista.append('B')
lista.append('L')
lista.append('E')
lista.append('M')
lista.append(' ')
lista.append('T')
lista.append('O')
lista.append(' ')
lista.append('B')
lista.append('E')
lista.append(' ')
lista.append('S')
lista.append('O')
lista.append('L')
lista.append('V')
lista.append('E')
lista.append('D')
x = int(input())
for i in range(x):
    if i == x-1:
        print(lista[i], end='\n')
    else:
        print(lista[i], end='')
